- hosts: ansible
  user: ansadmin

  tasks:
  - name: create docker image
    command: docker build -t simoganger/xyz-technologies:1.0.0 .
    args:
      chdir: /opt/docker 

  - name: push docker image
    command: docker push simoganger/xyz-technologies:1.0.0
