- hosts: ansible
  user: ansadmin

  tasks:
  - name: create docker image
    command: docker build -t simoganger/xyz-technologies:1.0.0 .
    args:
      chdir: /opt/docker 

  - name: push docker image
    command: docker push simoganger/xyz-technologies:1.0.0

  - name: create deployment on kubernetes
    command: kubectl apply -f ./k8s/deployment.yml
    args:
      chdir: /opt/docker

  - name: create service on kubernetes
    command: kubectl apply -f ./k8s/service.yml
    args:
      chdir: /opt/docker