apiVersion: v1
kind: Service
metadata:
  name: xyz-service
  labels:
    app: xyz-tech-app
spec:
  selector:
    app: xyz-tech-app

  ports:
    - port: 8080
      targetPort: 8080
      
  type: LoadBalancer